export type BrainrotEntry = {
  id: number;
  name: string;
  description: string;
  ingredients: string[];
  instructions: string[];
  difficulty: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  tags: string[];
};

export type BrainrotDB = {
  desserts: BrainrotEntry[];
  comfortFood: BrainrotEntry[];
  healthy: BrainrotEntry[];
  breakfast: BrainrotEntry[];
  snacks: BrainrotEntry[];
};

export const brainrotRecipes: BrainrotDB = {
  desserts: [
    {
      id: 1,
      name: "Skibidi Toilet Chocolate Cake",
      description: "A bussin' chocolate cake that's giving major W energy",
      ingredients: [
        "2 cups all-purpose flour",
        "2 cups sugar (no cap)",
        "3/4 cup cocoa powder (the good stuff fr fr)",
        "2 tsp baking soda",
        "1 tsp baking powder",
        "1 tsp salt (just a smidge)",
        "2 eggs (cage-free and slay)",
        "1 cup buttermilk (or milk with vinegar)",
        "1 cup hot water (respectfully)",
        "1/2 cup vegetable oil",
        "2 tsp vanilla extract (chef's kiss)",
      ],
      instructions: [
        "Preheat oven to 350°F (no lowkey temperatures here)",
        "Mix all dry ingredients together - they're about to go crazy",
        "Add eggs, buttermilk, oil, and vanilla. Beat it like it owes you Robux",
        "Stir in hot water (batter will be thin but trust the process bestie)",
        "Pour into greased pans and bake for 30-35 mins",
        "Let it cool or you'll get cooked yourself",
        "Frost with your fave icing and serve. It's giving delicious",
      ],
      difficulty: "Mid",
      prepTime: "15 mins",
      cookTime: "35 mins",
      servings: 12,
      tags: ["chocolate", "cake", "omega-bussin"],
    },
    {
      id: 2,
      name: "Rizz-Berry Cheesecake",
      description: "This cheesecake has more rizz than a level 10 gyatt",
      ingredients: [
        "2 cups graham cracker crumbs (crushed with aggression)",
        "1/2 cup melted butter (liquid gold fr)",
        "32 oz cream cheese (softened, not stiff)",
        "1 cup sugar (sweet like your personality)",
        "1 tsp vanilla (the vibe setter)",
        "4 eggs (unborn chickens respectfully)",
        "2 cups mixed berries (strawberries, blueberries, raspberries)",
        "1/4 cup berry jam (for the drip)",
      ],
      instructions: [
        "Mix graham crackers and butter, press into pan. It's giving foundation",
        "Beat cream cheese until smooth (no lumps allowed in this house)",
        "Add sugar and vanilla, mix until it's serving consistency",
        "Add eggs one at a time (they're joining the party individually)",
        "Pour over crust and bake at 325°F for 55 mins",
        "Let it chill in the fridge for 4 hours minimum (patience is a virtue)",
        "Top with berries and jam. Absolutely devious work",
      ],
      difficulty: "Try-hard",
      prepTime: "20 mins",
      cookTime: "55 mins",
      servings: 10,
      tags: ["cheesecake", "berries", "sigma-approved"],
    },
  ],
  comfortFood: [
    {
      id: 3,
      name: "Bussin' Mac and Cheese",
      description: "Mac and cheese that hits different. Absolutely goated",
      ingredients: [
        "1 lb elbow macaroni (the OGs)",
        "4 cups shredded cheddar cheese (sharp like your comeback)",
        "2 cups milk (whole milk slaps harder)",
        "1/4 cup butter (the real MVP)",
        "1/4 cup flour (thickening agent fr)",
        "1 tsp mustard powder (secret weapon)",
        "Salt and pepper (to taste, no cap)",
        "1 cup breadcrumbs (for the crunch factor)",
      ],
      instructions: [
        "Cook macaroni according to package. Don't overcook it or it's an L",
        "Melt butter in a saucepan (medium heat, we're not trying to start a fire)",
        "Add flour and whisk for 1 min. It's thickening era",
        "Slowly add milk while whisking (this is where boys become men)",
        "Add mustard powder, salt, and pepper. Season that bad boy",
        "Remove from heat and add 3 cups cheese. Stir until melted",
        "Mix with pasta, top with remaining cheese and breadcrumbs",
        "Bake at 350°F for 20 mins. The crunch is immaculate",
      ],
      difficulty: "Easy dub",
      prepTime: "15 mins",
      cookTime: "30 mins",
      servings: 8,
      tags: ["pasta", "cheese", "no-skips"],
    },
    {
      id: 4,
      name: "Sigma Grindset Chicken Tendies",
      description: "Tendies so fire they'll make you question reality",
      ingredients: [
        "2 lbs chicken tenders (the chosen ones)",
        "2 cups buttermilk (for marinating like a boss)",
        "2 cups flour (the coating of champions)",
        "2 tsp paprika (spice is nice)",
        "1 tsp garlic powder (vampire repellent)",
        "1 tsp onion powder (flavor bomb)",
        "1 tsp cayenne (optional: for those who can handle the heat)",
        "Salt and pepper (the basics)",
        "Oil for frying (the transformation medium)",
      ],
      instructions: [
        "Marinate chicken in buttermilk for at least 2 hours (patience = W)",
        "Mix flour with all spices in a bowl. This is the drip",
        "Heat oil to 350°F (too hot and you'll get cooked, too cold and it's mid)",
        "Coat each tender in flour mixture (double coat if you're feeling devious)",
        "Fry for 6-8 mins until golden. They should be giving crispy",
        "Drain on paper towels (we don't need that extra grease)",
        "Serve with your sauce of choice. Absolutely cinema",
      ],
      difficulty: "Moderate grind",
      prepTime: "2 hours 15 mins",
      cookTime: "20 mins",
      servings: 6,
      tags: ["chicken", "fried", "goated-with-the-sauce"],
    },
    {
      id: 5,
      name: "Fanum Tax Loaded Fries",
      description: "Loaded fries so good they'll get fanum taxed immediately",
      ingredients: [
        "2 lbs frozen fries (or make your own if you're built different)",
        "1 lb ground beef (the protein)",
        "1 packet taco seasoning (spice up your life)",
        "2 cups shredded cheese (more cheese = more W)",
        "1 cup sour cream (the cooling agent)",
        "1/2 cup jalapeños (for the brave)",
        "1/4 cup green onions (the garnish that matters)",
        "Salsa (as much as your heart desires)",
      ],
      instructions: [
        "Cook fries according to package until crispy (soggy fries are an L)",
        "Brown ground beef and add taco seasoning (let it cook down fr)",
        "Layer fries on a baking sheet (foundation is key)",
        "Add beef, cover with cheese (be generous, you deserve it)",
        "Bake at 400°F until cheese melts (5 mins max)",
        "Top with sour cream, jalapeños, onions, and salsa",
        "Serve immediately before someone fanum taxes your plate",
      ],
      difficulty: "Entry level",
      prepTime: "10 mins",
      cookTime: "25 mins",
      servings: 4,
      tags: ["fries", "loaded", "omega-bussin"],
    },
  ],
  healthy: [
    {
      id: 6,
      name: "Gyatt Damn Green Smoothie",
      description:
        "A smoothie so healthy it'll have you saying gyatt about your own glow-up",
      ingredients: [
        "2 cups spinach (the green machine)",
        "1 banana (for the thickness)",
        "1 cup frozen mango (tropical vibes)",
        "1/2 avocado (healthy fats are serving)",
        "1 cup almond milk (or any milk that slaps)",
        "1 tbsp chia seeds (the tiny powerhouses)",
        "1 tbsp honey (natural sweetness fr)",
        "Ice cubes (for that chill factor)",
      ],
      instructions: [
        "Add spinach and almond milk to blender first (liquid base is key)",
        "Add banana, mango, and avocado (the flavor profile)",
        "Toss in chia seeds and honey (boost mode activated)",
        "Add ice cubes (depending on how thick you want it)",
        "Blend until smooth (no chunks allowed in this establishment)",
        "Pour into a glass and drink immediately",
        "Your skin will be glowing like you just hit a lick",
      ],
      difficulty: "No effort W",
      prepTime: "5 mins",
      cookTime: "0 mins",
      servings: 2,
      tags: ["smoothie", "vegan", "glow-up-juice"],
    },
    {
      id: 7,
      name: "Slay Queen Salmon Bowl",
      description: "A salmon bowl that's giving health and wealth",
      ingredients: [
        "2 salmon fillets (wild-caught and unbothered)",
        "2 cups cooked quinoa (the ancient grain)",
        "2 cups mixed greens (arugula, spinach, whatever's popping)",
        "1 avocado sliced (the creamy goodness)",
        "1 cup cherry tomatoes halved (bite-sized flavor bombs)",
        "1/4 cup edamame (protein pods)",
        "2 tbsp olive oil (liquid gold)",
        "1 lemon (for the zing)",
        "Salt, pepper, garlic powder (the holy trinity)",
      ],
      instructions: [
        "Season salmon with salt, pepper, and garlic powder (coat it good)",
        "Heat olive oil in a pan over medium heat",
        "Cook salmon 4-5 mins per side (don't overcook or it's cooked)",
        "While salmon cooks, prep your bowls with quinoa base",
        "Add greens, tomatoes, edamame, and avocado (arrange it aesthetically)",
        "Place salmon on top when done (it's giving centerpiece)",
        "Squeeze lemon over everything (that acid cuts through)",
        "Drizzle with more olive oil if desired. Absolutely immaculate",
      ],
      difficulty: "Intermediate slay",
      prepTime: "15 mins",
      cookTime: "10 mins",
      servings: 2,
      tags: ["salmon", "bowl", "omega-3s", "main-character-energy"],
    },
    {
      id: 8,
      name: "Mewing-Approved Overnight Oats",
      description:
        "Oats so good they'll strengthen your jawline through sheer nutrition",
      ingredients: [
        "1 cup rolled oats (the base of legends)",
        "1 cup milk of choice (dairy or plant, your kingdom)",
        "1/2 cup Greek yogurt (protein packed)",
        "1 tbsp chia seeds (the expansion pack)",
        "1 tbsp honey or maple syrup (sweet dreams are made of this)",
        "1/2 tsp vanilla extract (the vibe)",
        "1/2 cup berries (strawberries, blueberries, go crazy)",
        "2 tbsp almond butter (optional but recommended)",
      ],
      instructions: [
        "Mix oats, milk, yogurt, chia seeds in a jar (mason jars hit different)",
        "Add honey and vanilla (stir it with purpose)",
        "Cover and refrigerate overnight (let time do the work)",
        "In the morning, stir and add berries on top",
        "Drizzle with almond butter (if you're feeling devious)",
        "Eat straight from the jar or bowl it up",
        "Your jawline will thank you (mewing optional but encouraged)",
      ],
      difficulty: "Zero skill required",
      prepTime: "5 mins",
      cookTime: "0 mins (just waiting)",
      servings: 1,
      tags: ["breakfast", "meal-prep", "no-cook", "jawline-fuel"],
    },
  ],
  breakfast: [
    {
      id: 9,
      name: "No Cap Pancake Stack",
      description: "Pancakes so fluffy they're literally on another level",
      ingredients: [
        "2 cups flour (all-purpose is clutch)",
        "2 tbsp sugar (sweetness factor)",
        "2 tsp baking powder (the rise is real)",
        "1/2 tsp salt (just a pinch fr)",
        "2 eggs (the binder)",
        "1 3/4 cups milk (whole milk slaps)",
        "1/4 cup melted butter (liquid gold status)",
        "1 tsp vanilla (the secret ingredient)",
        "Butter for pan (the non-stick guardian)",
      ],
      instructions: [
        "Mix flour, sugar, baking powder, and salt (the dry squad)",
        "Whisk eggs, milk, butter, and vanilla separately (the wet crew)",
        "Pour wet into dry and stir until just combined (lumps are okay, chill)",
        "Heat pan on medium, butter it up (this is crucial)",
        "Pour 1/4 cup batter per pancake (sizing matters)",
        "Cook until bubbles form, then flip (patience is key)",
        "Stack 'em high and serve with syrup. It's giving breakfast of champions",
      ],
      difficulty: "Easy W",
      prepTime: "10 mins",
      cookTime: "20 mins",
      servings: 4,
      tags: ["pancakes", "breakfast", "bussin"],
    },
    {
      id: 10,
      name: "Unc's Legendary Breakfast Burrito",
      description: "A breakfast burrito that'll have you saying 'what the sigma'",
      ingredients: [
        "4 large flour tortillas (the wrap game)",
        "8 eggs scrambled (the protein base)",
        "1 lb breakfast sausage (the flavor carrier)",
        "2 cups shredded cheese (never skimp on cheese)",
        "1 cup diced potatoes (crispy is mandatory)",
        "1/2 cup diced bell peppers (color and crunch)",
        "1/4 cup diced onions (flavor depth)",
        "Salsa and sour cream (the finishing touch)",
      ],
      instructions: [
        "Cook potatoes until crispy (this takes time but it's worth it)",
        "Brown sausage and set aside (drain the grease, we're not animals)",
        "Sauté peppers and onions until soft (flavor foundation)",
        "Scramble eggs in the same pan (one pan gang)",
        "Warm tortillas (microwave 20 secs or pan heat)",
        "Layer eggs, sausage, potatoes, peppers, onions, cheese",
        "Roll up tight like you mean it (burrito technique matters)",
        "Optional: pan fry the burrito for crispy exterior",
        "Serve with salsa and sour cream. Absolutely cinema",
      ],
      difficulty: "Moderate grind",
      prepTime: "15 mins",
      cookTime: "25 mins",
      servings: 4,
      tags: ["burrito", "breakfast", "protein-packed", "unc-approved"],
    },
  ],
  snacks: [
    {
      id: 11,
      name: "Ohio Final Boss Nachos",
      description: "Nachos so legendary they're the final boss of snack time",
      ingredients: [
        "1 bag tortilla chips (the foundation)",
        "2 cups shredded cheese (go wild)",
        "1 can black beans drained (protein boost)",
        "1 cup salsa (mild, medium, or spicy - you choose)",
        "1/2 cup sour cream (the cooling agent)",
        "1/4 cup jalapeños (optional: only if you're built different)",
        "1/4 cup olives sliced (optional)",
        "2 green onions sliced (the garnish)",
        "Guacamole (homemade or store-bought, no judgment)",
      ],
      instructions: [
        "Spread chips on a baking sheet (even distribution is key)",
        "Sprinkle beans evenly over chips (protein placement)",
        "Cover everything with cheese (be generous, you only live once)",
        "Bake at 350°F for 10 mins until cheese melts",
        "Remove and add dollops of sour cream and salsa",
        "Top with jalapeños, olives, and green onions",
        "Serve with guac on the side. These are absolutely devious",
      ],
      difficulty: "Entry level",
      prepTime: "5 mins",
      cookTime: "10 mins",
      servings: 6,
      tags: ["nachos", "snack", "party-food", "final-boss"],
    },
    {
      id: 12,
      name: "Goated Garlic Bread",
      description: "Garlic bread that's giving Michelin star energy",
      ingredients: [
        "1 French baguette (the canvas)",
        "1/2 cup butter softened (the base)",
        "4 cloves garlic minced (the star of the show)",
        "2 tbsp fresh parsley chopped (the green queen)",
        "1/4 cup parmesan cheese (the umami bomb)",
        "1/2 tsp salt (the enhancer)",
        "1/4 tsp black pepper (the spice)",
      ],
      instructions: [
        "Preheat oven to 375°F (get that heat going)",
        "Mix butter, garlic, parsley, parmesan, salt, pepper (the spread)",
        "Slice baguette in half lengthwise (commitment to flavor)",
        "Spread mixture generously on both halves (don't be shy)",
        "Wrap in foil and bake for 10 mins",
        "Unwrap, broil for 2-3 mins until crispy (watch it closely)",
        "Slice and serve. Your kitchen will smell absolutely divine",
      ],
      difficulty: "No cap easy",
      prepTime: "10 mins",
      cookTime: "15 mins",
      servings: 8,
      tags: ["garlic-bread", "side", "goated"],
    },
  ],
};


